"""Signal_CGO — 资本利得突出量

Category : 行为金融因子-处置效应
Operator : turnover_weighted_price
Direction: -1 负相关
Source   : cgo.txt

Formula
-------
RP_t = (1/k) * Σ_{n=0}^{T-1} [ V_{t-n} * Π_{s=1}^{n-1} (1 - V_{t-n+s}) ] * P_{t-n}
CGO_{i,t} = (Close_{i,t} - RP_t) / Close_{i,t}

Variable -> company data name (datadict.example.com)
------------------------------------------------
  V_t        t日的换手率   -> DailyQuote: TradeVolume / NULLIF(FloatShares, 0)
  Close      收盘价      -> DailyQuote.ClosePx
  P_t        VWAP均价   -> DailyQuote: TradeValue / NULLIF(TradeVolume, 0)
  k          权重系数，用于保证计算RP_t时的权重和等于1。 -> (parameter)

NOTE: Auto-generated by factor-forge. Review before production use.
"""

import warnings
from typing import Final

import duckdb
import numpy as np
import pandas as pd

import function

warnings.filterwarnings("ignore", module="connectorx")

MIN_VALID_VALUE: Final = 1000  # min number of non-null values
SIGNAL_FILE: Final = "runner_value_30180.json"
SIGNAL_CHECK_FILE: Final = "check_30180.json"
LOOKBACK: Final = 120


def read_daily_data(start_date: str, end_date: str):
    """Read daily quote data (company columns via datadict.example.com)."""
    sql = f"""
        SELECT
            InnerID,
            DataDate,
            ClosePx,
            TradeVolume / NULLIF(FloatShares, 0) AS turnover,
            TradeValue / NULLIF(TradeVolume, 0) AS vwap
        FROM LegacyDB.dbo.DailyQuote
        WHERE DataDate BETWEEN '{start_date}' AND '{end_date}'
          AND IsTradeDay = 1
          AND IsSuspended = 0
          AND ClosePx IS NOT NULL
        ORDER BY InnerID, DataDate
    """
    return function.read_sql(sql)


def calc_factor_data(daily_data, lookback: int = LOOKBACK):
    """Turnover-weighted holding-cost reference price, then average gain.

    RP_t = weighted mean of past prices with turnover * survival weights;
    value_t = (close_t - RP_t) / close_t.
    """
    records = []
    grouped = (
        daily_data.sort_values(["InnerID", "DataDate"])
        .groupby("InnerID", sort=False)
    )
    for inner_code, g in grouped:
        close = g["close"].to_numpy(dtype=float)
        tv = g["turnover"].clip(0.0, 1.0).fillna(0.0).to_numpy(dtype=float)
        pv = g["vwap"].fillna(g["close"]).to_numpy(dtype=float)
        n = len(close)
        rp = np.full(n, np.nan)
        for t in range(lookback, n):
            wsum, wp, survival = 0.0, 0.0, 1.0
            for lag in range(lookback):
                w = tv[t - lag] * survival
                wp += w * pv[t - lag]
                wsum += w
                survival *= 1.0 - tv[t - lag]
            rp[t] = wp / wsum if wsum > 1e-12 else pv[t]
        value = (close[-1] - rp[-1]) / close[-1] if close[-1] else np.nan
        records.append({
            "InnerID": inner_code,
            "DataDate": g["DataDate"].iloc[-1],
            "runner_value": value,
        })
    return pd.DataFrame.from_records(records)


def build_signal_data(factor_data, daily_security_info):
    sql = """
        SELECT
            daily_security_info.SecCode AS runner_code,
            factor_data.runner_value
        FROM daily_security_info
        LEFT JOIN factor_data USING (InnerID)
    """
    return duckdb.sql(sql).df().filter(items=["runner_code", "runner_value"])


def get_signal(date):
    trading_date = function.read_trading_date(date)
    daily_security_info = function.read_daily_security_info(trading_date)
    trading_dates = function.read_tradingdays(trading_date, 121)
    start_date = min(trading_dates).strftime("%Y-%m-%d")
    end_date = max(trading_dates).strftime("%Y-%m-%d")

    untradable = (
        function.read_untradable(start_date, end_date)
        .rename(columns={"TradeDate": "DataDate"})
        .filter(["DataDate", "InnerID"])
        .assign(is_untradable=1)
    )

    daily_data = read_daily_data(start_date, end_date)
    factor_data = calc_factor_data(daily_data)
    factor_data = (
        factor_data
        .merge(untradable, on=["DataDate", "InnerID"], how="left")
        .query("is_untradable.isna()", engine="python")
        .drop(columns=["is_untradable"])
    )
    return build_signal_data(factor_data, daily_security_info)


def main(date, output_dir):
    signal = get_signal(date)
    function.save_signal(
        signal, output_dir, SIGNAL_FILE, SIGNAL_CHECK_FILE, MIN_VALID_VALUE
    )
