"""Signal_VOL — 已实现波动率因子

Category : 已实现波动率因子
Operator : volatility
Direction: -1 负相关
Source   : volatility.txt

Formula
-------
VOL_{i,t} = std( r_{i,t-20:t} ) * sqrt(252)

Variable -> company data name (datadict.example.com)
------------------------------------------------
  r_{i,t}    t日的日收益率，由收盘价计算； -> DailyQuote.ClosePx
  std        滚动窗口内的标准差 -> (parameter)

NOTE: Auto-generated by factor-forge. Review before production use.
"""

import warnings
from typing import Final

import duckdb
import numpy as np
import pandas as pd

import function

warnings.filterwarnings("ignore", module="connectorx")

MIN_VALID_VALUE: Final = 1000  # min number of non-null values
SIGNAL_FILE: Final = "runner_value_0.json"
SIGNAL_CHECK_FILE: Final = "check_0.json"
WINDOW: Final = 20


def read_daily_data(start_date: str, end_date: str):
    """Read daily quote data (company columns via datadict.example.com)."""
    sql = f"""
        SELECT
            InnerID,
            DataDate,
            ClosePx
        FROM LegacyDB.dbo.DailyQuote
        WHERE DataDate BETWEEN '{start_date}' AND '{end_date}'
          AND IsTradeDay = 1
          AND IsSuspended = 0
          AND ClosePx IS NOT NULL
        ORDER BY InnerID, DataDate
    """
    return function.read_sql(sql)


def calc_factor_data(daily_data, window: int = WINDOW):
    """Annualized rolling standard deviation of daily returns."""
    records = []
    grouped = (
        daily_data.sort_values(["InnerID", "DataDate"])
        .groupby("InnerID", sort=False)
    )
    for inner_code, g in grouped:
        vol = g["close"].pct_change().rolling(window).std() * np.sqrt(252)
        records.append({
            "InnerID": inner_code,
            "DataDate": g["DataDate"].iloc[-1],
            "runner_value": float(vol.iloc[-1]) if len(vol) else np.nan,
        })
    return pd.DataFrame.from_records(records)


def build_signal_data(factor_data, daily_security_info):
    sql = """
        SELECT
            daily_security_info.SecCode AS runner_code,
            factor_data.runner_value
        FROM daily_security_info
        LEFT JOIN factor_data USING (InnerID)
    """
    return duckdb.sql(sql).df().filter(items=["runner_code", "runner_value"])


def get_signal(date):
    trading_date = function.read_trading_date(date)
    daily_security_info = function.read_daily_security_info(trading_date)
    trading_dates = function.read_tradingdays(trading_date, 22)
    start_date = min(trading_dates).strftime("%Y-%m-%d")
    end_date = max(trading_dates).strftime("%Y-%m-%d")

    untradable = (
        function.read_untradable(start_date, end_date)
        .rename(columns={"TradeDate": "DataDate"})
        .filter(["DataDate", "InnerID"])
        .assign(is_untradable=1)
    )

    daily_data = read_daily_data(start_date, end_date)
    factor_data = calc_factor_data(daily_data)
    factor_data = (
        factor_data
        .merge(untradable, on=["DataDate", "InnerID"], how="left")
        .query("is_untradable.isna()", engine="python")
        .drop(columns=["is_untradable"])
    )
    return build_signal_data(factor_data, daily_security_info)


def main(date, output_dir):
    signal = get_signal(date)
    function.save_signal(
        signal, output_dir, SIGNAL_FILE, SIGNAL_CHECK_FILE, MIN_VALID_VALUE
    )
