"""Codegen: Factor JSON -> executable Python factor code.

Given a structured Factor, emit a self-contained Python module implementing it.
Known operators map to vetted implementations; unknown ones produce a documented
skeleton (formula + variable mappings + TODO) rather than guessing blindly.

Every generated module:
  * carries provenance (formula, variable->data-field map, direction, source)
  * exposes a single function named after the factor
  * consumes only the data fields declared in the Factor (close/turnover/...)
  * returns a pandas Series aligned to the input index
"""

from __future__ import annotations

from typing import Dict, List

from .schema import Factor

# ---------------------------------------------------------------------------
# per-operator implementation templates
# ---------------------------------------------------------------------------
_HEADER = '''"""{name} — {name_cn}

Category : {category}
Operator : {operator}
Direction: {direction} {direction_note}
Source   : {source}

Formula
-------
{formula}

Variable -> data field
----------------------
{varmap}

NOTE: Auto-generated by factor-forge from the structured factor JSON.
Review before production use.
"""

import numpy as np
import pandas as pd

'''

_TEMPLATES: Dict[str, str] = {
    # CGO-style: turnover-weighted reference (holding-cost) price
    "turnover_weighted_price": '''
def {name}(close, turnover, price=None, lookback={lookback}):
    """Turnover-weighted holding-cost factor.

    Computes a reference price RP_t as the turnover-weighted average purchase
    price of the shares still held at t, then measures the holder's average
    gain/loss relative to the current price.
    """
    close = pd.Series(close).astype(float)
    turnover = pd.Series(turnover).astype(float).clip(0.0, 1.0).reindex(close.index)
    price = pd.Series(price).astype(float) if price is not None else close

    n = len(close)
    rp = np.full(n, np.nan)
    cv = close.values
    tv = turnover.values
    pv = price.values
    for t in range(lookback, n):
        wsum = 0.0
        wp = 0.0
        survival = 1.0
        for lag in range(lookback):
            v = tv[t - lag]
            if not np.isfinite(v):
                v = 0.0
            w = v * survival
            wp += w * pv[t - lag]
            wsum += w
            survival *= (1.0 - v)
        rp[t] = (wp / wsum) if wsum > 1e-12 else pv[t]
    rp = pd.Series(rp, index=close.index)
    out = (close - rp) / close
    return out
''',

    "momentum": '''
def {name}(close, lag={lag}, skip={skip}):
    """Price momentum: return over [t-lag, t-skip]."""
    close = pd.Series(close).astype(float)
    out = close.shift(skip) / close.shift(lag) - 1.0
    return out
''',

    "reversal": '''
def {name}(close, period={period}):
    """Short-term reversal: negative of the most recent `period` return."""
    close = pd.Series(close).astype(float)
    out = -close.pct_change(periods=period)
    return out
''',

    "volatility": '''
def {name}(close, window={window}, annualize=True):
    """Realized volatility over a rolling window."""
    close = pd.Series(close).astype(float)
    ret = close.pct_change()
    vol = ret.rolling(window).std()
    if annualize:
        vol = vol * np.sqrt(252)
    return vol
''',
}

_GENERIC = '''
def {name}(**inputs):
    """[GENERIC — not yet implemented]

    The formula below was extracted from the report but no operator template
    matched it. Implement the body using the provided inputs.

    Required inputs (data fields): {fields}
    """
    # TODO: implement
    # Formula:
    # {formula_indented}
    raise NotImplementedError("{name} codegen template not implemented yet")
'''


def _varmap_block(fac: Factor) -> str:
    if not fac.variables:
        return "  (no variables declared)"
    rows = []
    for v in fac.variables:
        rows.append(f"  {v.symbol:<10} -> {v.data_field or '?':<12} ({v.name_cn})")
    return "\n".join(rows)


def _params(fac: Factor) -> Dict:
    """Defaults per operator, overridable by Factor.params."""
    op = fac.operator
    defaults = {
        "turnover_weighted_price": {"lookback": 120},
        "momentum": {"lag": 12, "skip": 1},
        "reversal": {"period": 1},
        "volatility": {"window": 20},
    }.get(op, {})
    defaults.update(fac.params or {})
    return defaults


def generate(fac: Factor) -> str:
    """Generate a Python module implementing the Factor."""
    p = _params(fac)
    header = _HEADER.format(
        name=fac.name, name_cn=fac.name_cn, category=fac.category or "-",
        operator=fac.operator or "generic",
        direction={1: "+1", -1: "-1", 0: "0"}.get(fac.direction, "?"),
        direction_note=fac.direction_note or "",
        source=fac.source or "-",
        formula=fac.formula or "(none)",
        varmap=_varmap_block(fac),
    )
    tmpl = _TEMPLATES.get(fac.operator)
    if tmpl is not None:
        body = tmpl.format(name=fac.name, **p)
    else:
        formula_indented = "\n    # ".join((fac.formula or "").splitlines())
        body = _GENERIC.format(name=fac.name,
                               fields=", ".join(fac.required_fields()) or "n/a",
                               formula_indented=formula_indented)
    return header + body


def generate_to_file(fac: Factor, path: str) -> str:
    code = generate(fac)
    with open(path, "w", encoding="utf-8") as f:
        f.write(code)
    return path
