"""Company codegen: Factor -> signal-library repository (core.py centric).

The company factor repository (GitLab signal library, Gaea runner) looks like:

    Signal_XXX/
    ├── core.py          # factor logic: read_daily_data / calc_factor_data /
    │                    #   build_signal_data / get_signal / main
    ├── function.py      # standard data-access layer (shared, verbatim copy)
    ├── main.py          # click CLI (-d date -o output -r rawdata ...)
    ├── manifest.json    # Gaea runner/project/dag config
    ├── rawdata.json     # DB connection config (placeholders here)
    ├── .gitlab-ci.yml   # ci-template Auto-Trigger
    ├── materials/spec.json
    └── README.md

The generated core.py follows the vetted house pattern (see e.g.
Signal_AccumulationDistributionIndex): company data names in the SQL,
per-stock factor calculation, output as runner_code/runner_value written by
function.save_signal into runner_value_<runner_id>.json.
"""

from __future__ import annotations

import json
import os
from typing import Dict, List, Optional

from .schema import Factor, OPERATOR_FIELDS
from .datadict import DictBinding, BUILTIN_BINDINGS, UNBOUND_FIELDS

_TEMPLATES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              "templates")

TABLE_QUALIFIED = "LegacyDB.dbo.DailyQuote"

# ---------------------------------------------------------------------------
# core.py building blocks
# ---------------------------------------------------------------------------
_CORE_HEADER = '''"""{runner_name} — {name_cn}

Category : {category}
Operator : {operator}
Direction: {direction} {direction_note}
Source   : {source}

Formula
-------
{formula}

Variable -> company data name (datadict.example.com)
------------------------------------------------
{varmap}

NOTE: Auto-generated by factor-forge. Review before production use.
"""

import warnings
from typing import Final

import numpy as np
import pandas as pd

import function

warnings.filterwarnings("ignore", module="connectorx")

MIN_VALID_VALUE: Final = 1000  # min number of non-null values
SIGNAL_FILE: Final = "runner_value_{runner_id}.json"
SIGNAL_CHECK_FILE: Final = "check_{runner_id}.json"
'''

_READ_DAILY = '''

def read_daily_data(start_date: str, end_date: str):
    """Read daily quote data (company columns via datadict.example.com)."""
    sql = f"""
        SELECT
{select_list}
        FROM {table}
        WHERE DataDate BETWEEN '{{start_date}}' AND '{{end_date}}'
          AND IsTradeDay = 1
          AND IsSuspended = 0
          AND ClosePx IS NOT NULL
        ORDER BY InnerID, DataDate
    """
    return function.read_sql(sql)
'''

_BUILD_SIGNAL = '''

def build_signal_data(factor_data, daily_security_info):
    sql = """
        SELECT
            daily_security_info.SecCode AS runner_code,
            factor_data.runner_value
        FROM daily_security_info
        LEFT JOIN factor_data USING (InnerID)
    """
    return duckdb.sql(sql).df().filter(items=["runner_code", "runner_value"])
'''

_GET_SIGNAL = '''

def get_signal(date):
    trading_date = function.read_trading_date(date)
    daily_security_info = function.read_daily_security_info(trading_date)
    trading_dates = function.read_tradingdays(trading_date, {hist_days})
    start_date = min(trading_dates).strftime("%Y-%m-%d")
    end_date = max(trading_dates).strftime("%Y-%m-%d")

    untradable = (
        function.read_untradable(start_date, end_date)
        .rename(columns={{"TradeDate": "DataDate"}})
        .filter(["DataDate", "InnerID"])
        .assign(is_untradable=1)
    )

    daily_data = read_daily_data(start_date, end_date)
    factor_data = calc_factor_data(daily_data)
    factor_data = (
        factor_data
        .merge(untradable, on=["DataDate", "InnerID"], how="left")
        .query("is_untradable.isna()", engine="python")
        .drop(columns=["is_untradable"])
    )
    return build_signal_data(factor_data, daily_security_info)


def main(date, output_dir):
    signal = get_signal(date)
    function.save_signal(
        signal, output_dir, SIGNAL_FILE, SIGNAL_CHECK_FILE, MIN_VALID_VALUE
    )
'''

# ---------------------------------------------------------------------------
# per-operator calc implementations (consume aliased canonical columns)
# ---------------------------------------------------------------------------
_CALC_TURNOVER_WEIGHTED_PRICE = '''

def calc_factor_data(daily_data, lookback: int = LOOKBACK):
    """Turnover-weighted holding-cost reference price, then average gain.

    RP_t = weighted mean of past prices with turnover * survival weights;
    value_t = (close_t - RP_t) / close_t.
    """
    records = []
    grouped = (
        daily_data.sort_values(["InnerID", "DataDate"])
        .groupby("InnerID", sort=False)
    )
    for inner_code, g in grouped:
        close = g["close"].to_numpy(dtype=float)
        tv = g["turnover"].clip(0.0, 1.0).fillna(0.0).to_numpy(dtype=float)
        pv = g["vwap"].fillna(g["close"]).to_numpy(dtype=float)
        n = len(close)
        rp = np.full(n, np.nan)
        for t in range(lookback, n):
            wsum, wp, survival = 0.0, 0.0, 1.0
            for lag in range(lookback):
                w = tv[t - lag] * survival
                wp += w * pv[t - lag]
                wsum += w
                survival *= 1.0 - tv[t - lag]
            rp[t] = wp / wsum if wsum > 1e-12 else pv[t]
        value = (close[-1] - rp[-1]) / close[-1] if close[-1] else np.nan
        records.append({
            "InnerID": inner_code,
            "DataDate": g["DataDate"].iloc[-1],
            "runner_value": value,
        })
    return pd.DataFrame.from_records(records)
'''

_CALC_MOMENTUM = '''

def calc_factor_data(daily_data, lag: int = LAG, skip: int = SKIP):
    """Price momentum: close_{t-skip} / close_{t-lag} - 1."""
    data = daily_data.sort_values(["InnerID", "DataDate"]).copy()
    shifted_skip = data.groupby("InnerID")["close"].shift(skip)
    shifted_lag = data.groupby("InnerID")["close"].shift(lag)
    data["runner_value"] = shifted_skip / shifted_lag - 1.0
    return (
        data.groupby("InnerID", sort=False)
        .tail(1)
        .filter(items=["InnerID", "DataDate", "runner_value"])
        .reset_index(drop=True)
    )
'''

_CALC_REVERSAL = '''

def calc_factor_data(daily_data, period: int = PERIOD):
    """Short-term reversal: negative of the most recent `period` return."""
    data = daily_data.sort_values(["InnerID", "DataDate"]).copy()
    prev_close = data.groupby("InnerID")["close"].shift(period)
    data["runner_value"] = -(data["close"] / prev_close - 1.0)
    return (
        data.groupby("InnerID", sort=False)
        .tail(1)
        .filter(items=["InnerID", "DataDate", "runner_value"])
        .reset_index(drop=True)
    )
'''

_CALC_VOLATILITY = '''

def calc_factor_data(daily_data, window: int = WINDOW):
    """Annualized rolling standard deviation of daily returns."""
    records = []
    grouped = (
        daily_data.sort_values(["InnerID", "DataDate"])
        .groupby("InnerID", sort=False)
    )
    for inner_code, g in grouped:
        vol = g["close"].pct_change().rolling(window).std() * np.sqrt(252)
        records.append({
            "InnerID": inner_code,
            "DataDate": g["DataDate"].iloc[-1],
            "runner_value": float(vol.iloc[-1]) if len(vol) else np.nan,
        })
    return pd.DataFrame.from_records(records)
'''

_CALC_GENERIC = '''

def calc_factor_data(daily_data):
    """[GENERIC — not yet implemented]

    The formula below was extracted from the report but no operator template
    matched it. Implement the body and return a DataFrame with columns
    ["InnerID", "DataDate", "runner_value"].

    Formula:
    {formula_indented}

    Available inputs (daily_data columns): {fields}
    """
    # TODO: implement
    raise NotImplementedError("calc_factor_data not implemented yet")
'''

_OP_CALC = {
    "turnover_weighted_price": _CALC_TURNOVER_WEIGHTED_PRICE,
    "momentum": _CALC_MOMENTUM,
    "reversal": _CALC_REVERSAL,
    "volatility": _CALC_VOLATILITY,
}

# canonical fields each operator consumes (shared with datadict binding)
_OP_FIELDS = OPERATOR_FIELDS


def _needed_fields(fac: Factor) -> List[str]:
    """Ordered union of operator-implied fields and declared variable fields."""
    op = fac.operator or "generic"
    seen, out = set(), []
    for f in (_OP_FIELDS.get(op) or []) + fac.required_fields():
        if f and f not in seen:
            seen.add(f)
            out.append(f)
    return out

# default params + history length (read_tradingdays count) per operator
_OP_DEFAULTS = {
    "turnover_weighted_price": ({"lookback": 120}, lambda p: p["lookback"] + 1),
    "momentum": ({"lag": 12, "skip": 1}, lambda p: p["lag"] + 1),
    "reversal": ({"period": 1}, lambda p: p["period"] + 1),
    "volatility": ({"window": 20}, lambda p: p["window"] + 2),
    "generic": ({}, lambda p: 60),
}


def _params(fac: Factor) -> Dict:
    defaults, _ = _OP_DEFAULTS.get(fac.operator or "generic", ({}, None))
    defaults = dict(defaults)
    defaults.update(fac.params or {})
    return defaults


def _varmap_block(fac: Factor, bindings: Dict[str, DictBinding]) -> str:
    if not fac.variables:
        return "  (no variables declared)"
    rows = []
    for v in fac.variables:
        b = bindings.get(v.data_field)
        if not v.data_field:
            where = "(parameter)"
        elif b is None:
            if v.data_field in UNBOUND_FIELDS:
                where = "(fundamental field - bind before production)"
            else:
                where = "(UNBOUND - TODO, see datadict.example.com)"
        elif b.expr:
            where = f"{b.table}: {b.expr}"
        else:
            where = f"{b.table}.{b.column}"
        rows.append(f"  {v.symbol:<10} {v.name_cn:<8} -> {where}")
    return "\n".join(rows)


def _select_block(fac: Factor, bindings: Dict[str, DictBinding]) -> str:
    """SQL select list: InnerID/DataDate + one line per bound field."""
    lines = ["            InnerID,", "            DataDate,"]
    op = fac.operator or "generic"
    for field_name in _needed_fields(fac):
        b = bindings.get(field_name)
        if b is None:
            lines.append(f"            -- TODO: bind '{field_name}' "
                         f"via datadict.example.com")
            continue
        lines.append(f"            {b.select_expr},")
    return "\n".join(lines).rstrip(",\n")


def generate_corepy(fac: Factor, runner_id: int = 0,
                    runner_name: Optional[str] = None,
                    bindings: Optional[Dict[str, DictBinding]] = None) -> str:
    """Generate the company-format core.py for a Factor."""
    if bindings is None:
        bindings = {k: BUILTIN_BINDINGS[k]
                    for k in _needed_fields(fac) if k in BUILTIN_BINDINGS}
    op = fac.operator or "generic"
    params = _params(fac)
    _, hist_fn = _OP_DEFAULTS.get(op, ({}, lambda p: 60))

    name = runner_name or fac.name
    if not name.startswith("Signal_"):
        name = f"Signal_{name}"

    header = _CORE_HEADER.format(
        runner_name=name, name_cn=fac.name_cn or "-",
        category=fac.category or "-", operator=op,
        direction={1: "+1", -1: "-1", 0: "0"}.get(fac.direction, "?"),
        direction_note=fac.direction_note or "", source=fac.source or "-",
        formula=fac.formula or "(none)",
        varmap=_varmap_block(fac, bindings), runner_id=runner_id)

    const_lines = []
    if op == "turnover_weighted_price":
        const_lines.append(f"LOOKBACK: Final = {int(params['lookback'])}")
    elif op == "momentum":
        const_lines.append(f"LAG: Final = {int(params['lag'])}")
        const_lines.append(f"SKIP: Final = {int(params['skip'])}")
    elif op == "reversal":
        const_lines.append(f"PERIOD: Final = {int(params['period'])}")
    elif op == "volatility":
        const_lines.append(f"WINDOW: Final = {int(params['window'])}")
    consts = ("\n".join(const_lines) + "\n") if const_lines else ""

    read_daily = _READ_DAILY.format(select_list=_select_block(fac, bindings),
                                    table=TABLE_QUALIFIED)

    calc_tmpl = _OP_CALC.get(op)
    if calc_tmpl is not None:
        calc = calc_tmpl
    else:
        formula_indented = "\n    # ".join((fac.formula or "").splitlines())
        cols = []
        for f in _needed_fields(fac):
            b = bindings.get(f)
            cols.append(f if b is None else b.data_field)
        calc = _CALC_GENERIC.format(formula_indented=formula_indented,
                                    fields=", ".join(cols) or "n/a")

    body = header + consts + read_daily + calc + _BUILD_SIGNAL + \
        _GET_SIGNAL.format(hist_days=hist_fn(params))
    # build_signal_data uses duckdb; keep the import with the top block
    body = body.replace("import numpy as np\nimport pandas as pd\n",
                        "import duckdb\nimport numpy as np\n"
                        "import pandas as pd\n", 1)
    return body


# ---------------------------------------------------------------------------
# company spec.json conversion
# ---------------------------------------------------------------------------
def factor_to_company_spec(fac: Factor, runner_name: str) -> Dict:
    """Factor -> the spec.json schema used by signal-library repos."""
    formula_lines = [ln for ln in (fac.formula or "").splitlines() if ln.strip()]
    var_desc = "；".join(
        f"{v.symbol}: {v.description or v.name_cn}" for v in fac.variables)
    return {
        "signal_name": runner_name,
        "signal_name_raw": fac.name_cn,
        "signal_category": fac.category,
        "signal_formula_raw": " \\quad ".join(formula_lines),
        "signal_formula": formula_lines,
        "signal_variables_name": [v.symbol for v in fac.variables],
        "signal_formula_add": "",
        "signal_variables_name_add": [],
        "signal_variables_description": var_desc,
        "signal_description": fac.description,
        "signal_reference": fac.source,
        "human_feedback": "",
    }


# ---------------------------------------------------------------------------
# full repo scaffold
# ---------------------------------------------------------------------------
def _template(name: str) -> str:
    with open(os.path.join(_TEMPLATES_DIR, name), encoding="utf-8") as f:
        return f.read()


def generate_repo(fac: Factor, out_dir: str, runner_id: int = 0,
                  runner_name: Optional[str] = None,
                  bindings: Optional[Dict[str, DictBinding]] = None,
                  group: str = "momentum_factor") -> Dict[str, str]:
    """Write a full company signal-library repo scaffold. Returns file map."""
    name = runner_name or fac.name
    if not name.startswith("Signal_"):
        name = f"Signal_{name}"

    os.makedirs(os.path.join(out_dir, "materials"), exist_ok=True)
    written: Dict[str, str] = {}

    def put(rel: str, content: str) -> None:
        path = os.path.join(out_dir, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written[rel] = path

    put("core.py", generate_corepy(fac, runner_id=runner_id,
                                   runner_name=name, bindings=bindings))
    put("function.py", _template("function.py"))
    put("main.py", _template("main.py"))
    put(".gitlab-ci.yml", _template("gitlab-ci.yml"))
    put(".gitignore", _template("gitignore"))
    put("rawdata.json", _template("rawdata.json"))

    manifest = {
        "dependencies": [
            {"type": "table", "database": "DBCheck",
             "tables": [{"table": "LegacyDBOK", "recency": 0,
                         "daytype": "C"}]},
            {"type": "table", "database": "LegacyDB",
             "tables": [{"table": "DailyQuote", "recency": 0, "daytype": "C"},
                        {"table": "TradeCalendar", "recency": 0,
                         "daytype": "C"}]},
        ],
        "checks": [
            {"item": "min-munber-of-values", "value": 1000, "skip": "false"},
            {"item": "value-is-always-numeric", "value": "true",
             "skip": "false"},
            {"item": "no-negative-values", "value": "true", "skip": "true"},
            {"item": "no-duplicated-ticker", "value": "true",
             "skip": "false"},
            {"item": "ticker-history-check", "value": "true",
             "skip": "false"},
        ],
        "project_info": [{
            "project_id": 0,
            "project_name": name,
            "project_type": "signal",
            "git_server": "gitlab.example.com",
            "git_repo": f"signal-library/calendar/{group}/{name}.git",
            "config_tag": "",
        }],
        "runner_info": [{
            "runner_id": runner_id,
            "runner_name": name,
            "runner_type": "signal",
            "config_tag": "",
        }],
        "dag_info": [{
            "dag_id": f"{name}_0100",
            "dag_type": "signal_library",
            "start_time": "0100",
            "day_delay": 1,
            "check_dependency": 1,
            "insert_database": 1,
            "worker_image":
                "registry.example.com/ci/worker-py311:latest",
        }],
    }
    put("manifest.json", json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    put("materials/spec.json",
        json.dumps(factor_to_company_spec(fac, name),
                   ensure_ascii=False, indent=2) + "\n")
    put("README.md", _company_readme(fac, name, bindings))
    return written


def _company_readme(fac: Factor, runner_name: str,
                    bindings: Optional[Dict[str, DictBinding]]) -> str:
    b = bindings or {}
    req = []
    for field_name in _needed_fields(fac):
        bind = b.get(field_name)
        if bind is None:
            req.append(f"  - {field_name} (TODO: bind via datadict.example.com)")
        elif bind.expr:
            req.append(f"  - {bind.cn_name}: {bind.table}: {bind.expr}")
        else:
            req.append(f"  - {bind.cn_name}: {bind.table}.{bind.column}")
    var_rows = "\n".join(f"| {v.symbol} | {v.description or v.name_cn} |"
                         for v in fac.variables)
    return f"""# {fac.name_cn} ({runner_name})

## 因子概述

| 属性 | 说明 |
|------|------|
| **因子英文名** | `{runner_name}` |
| **因子中文名** | {fac.name_cn} |
| **因子类别** | {fac.category or '-'} |
| **方向** | {fac.direction:+d} {fac.direction_note} |
| **来源** | {fac.source or '-'} |

## 因子描述

{fac.description or '-'}

## 公式定义

```math
{(fac.formula or '').replace(chr(10), chr(10))}
```

## 变量说明

| 变量符号 | 说明 |
| --- | --- |
{var_rows or '| - | - |'}

## 数据要求（公司数据字典）

- **数据频率**：日频
- **所需字段**（datadict.example.com）：
{chr(10).join(req) or '  - (none)'}

NOTE: Auto-generated by factor-forge.
"""
