"""Signal_ILLIQ — Amihud非流动性因子

Category : Amihud非流动性因子
Operator : generic
Direction: +1 正相关
Source   : amihud.txt

Formula
-------
ILLIQ_{i,t} = mean_{s=t-20}^{t} ( |r_{i,s}| / Amount_{i,s} )

Variable -> company data name (datadict.example.com)
------------------------------------------------
  r_{i,s}    s日的收益率   -> DailyQuote.DailyReturn
  Amount_{i,s} s日的成交额   -> DailyQuote.TradeValue
  mean       过去20个交易日的均值 -> (parameter)

NOTE: Auto-generated by factor-forge. Review before production use.
"""

import warnings
from typing import Final

import duckdb
import numpy as np
import pandas as pd

import function

warnings.filterwarnings("ignore", module="connectorx")

MIN_VALID_VALUE: Final = 1000  # min number of non-null values
SIGNAL_FILE: Final = "runner_value_0.json"
SIGNAL_CHECK_FILE: Final = "check_0.json"


def read_daily_data(start_date: str, end_date: str):
    """Read daily quote data (company columns via datadict.example.com)."""
    sql = f"""
        SELECT
            InnerID,
            DataDate,
            DailyReturn,
            TradeValue
        FROM LegacyDB.dbo.DailyQuote
        WHERE DataDate BETWEEN '{start_date}' AND '{end_date}'
          AND IsTradeDay = 1
          AND IsSuspended = 0
          AND ClosePx IS NOT NULL
        ORDER BY InnerID, DataDate
    """
    return function.read_sql(sql)


def calc_factor_data(daily_data):
    """[GENERIC — not yet implemented]

    The formula below was extracted from the report but no operator template
    matched it. Implement the body and return a DataFrame with columns
    ["InnerID", "DataDate", "runner_value"].

    Formula:
    ILLIQ_{i,t} = mean_{s=t-20}^{t} ( |r_{i,s}| / Amount_{i,s} )

    Available inputs (daily_data columns): returns, amount
    """
    # TODO: implement
    raise NotImplementedError("calc_factor_data not implemented yet")


def build_signal_data(factor_data, daily_security_info):
    sql = """
        SELECT
            daily_security_info.SecCode AS runner_code,
            factor_data.runner_value
        FROM daily_security_info
        LEFT JOIN factor_data USING (InnerID)
    """
    return duckdb.sql(sql).df().filter(items=["runner_code", "runner_value"])


def get_signal(date):
    trading_date = function.read_trading_date(date)
    daily_security_info = function.read_daily_security_info(trading_date)
    trading_dates = function.read_tradingdays(trading_date, 60)
    start_date = min(trading_dates).strftime("%Y-%m-%d")
    end_date = max(trading_dates).strftime("%Y-%m-%d")

    untradable = (
        function.read_untradable(start_date, end_date)
        .rename(columns={"TradeDate": "DataDate"})
        .filter(["DataDate", "InnerID"])
        .assign(is_untradable=1)
    )

    daily_data = read_daily_data(start_date, end_date)
    factor_data = calc_factor_data(daily_data)
    factor_data = (
        factor_data
        .merge(untradable, on=["DataDate", "InnerID"], how="left")
        .query("is_untradable.isna()", engine="python")
        .drop(columns=["is_untradable"])
    )
    return build_signal_data(factor_data, daily_security_info)


def main(date, output_dir):
    signal = get_signal(date)
    function.save_signal(
        signal, output_dir, SIGNAL_FILE, SIGNAL_CHECK_FILE, MIN_VALID_VALUE
    )
