"""ILLIQ — Amihud非流动性因子

Category : Amihud非流动性因子
Operator : generic
Direction: +1 正相关
Source   : amihud.txt

Formula
-------
ILLIQ_{i,t} = mean_{s=t-20}^{t} ( |r_{i,s}| / Amount_{i,s} )

Variable -> data field
----------------------
  r_{i,s}    -> returns      (s日的收益率)
  Amount_{i,s} -> amount       (s日的成交额)
  mean       -> ?            (过去20个交易日的均值)

NOTE: Auto-generated by factor-forge from the structured factor JSON.
Review before production use.
"""

import numpy as np
import pandas as pd


def ILLIQ(**inputs):
    """[GENERIC — not yet implemented]

    The formula below was extracted from the report but no operator template
    matched it. Implement the body using the provided inputs.

    Required inputs (data fields): returns, amount
    """
    # TODO: implement
    # Formula:
    # ILLIQ_{i,t} = mean_{s=t-20}^{t} ( |r_{i,s}| / Amount_{i,s} )
    raise NotImplementedError("ILLIQ codegen template not implemented yet")
