"""CGO — 资本利得突出量

Category : 行为金融因子-处置效应
Operator : turnover_weighted_price
Direction: -1 负相关
Source   : cgo.txt

Formula
-------
RP_t = (1/k) * Σ_{n=0}^{T-1} [ V_{t-n} * Π_{s=1}^{n-1} (1 - V_{t-n+s}) ] * P_{t-n}
CGO_{i,t} = (Close_{i,t} - RP_t) / Close_{i,t}

Variable -> data field
----------------------
  V_t        -> turnover     (t日的换手率)
  Close      -> close        (收盘价)
  P_t        -> vwap         (VWAP均价)
  k          -> ?            (权重系数，用于保证计算RP_t时的权重和等于1。)

NOTE: Auto-generated by factor-forge from the structured factor JSON.
Review before production use.
"""

import numpy as np
import pandas as pd


def CGO(close, turnover, price=None, lookback=120):
    """Turnover-weighted holding-cost factor.

    Computes a reference price RP_t as the turnover-weighted average purchase
    price of the shares still held at t, then measures the holder's average
    gain/loss relative to the current price.
    """
    close = pd.Series(close).astype(float)
    turnover = pd.Series(turnover).astype(float).clip(0.0, 1.0).reindex(close.index)
    price = pd.Series(price).astype(float) if price is not None else close

    n = len(close)
    rp = np.full(n, np.nan)
    cv = close.values
    tv = turnover.values
    pv = price.values
    for t in range(lookback, n):
        wsum = 0.0
        wp = 0.0
        survival = 1.0
        for lag in range(lookback):
            v = tv[t - lag]
            if not np.isfinite(v):
                v = 0.0
            w = v * survival
            wp += w * pv[t - lag]
            wsum += w
            survival *= (1.0 - v)
        rp[t] = (wp / wsum) if wsum > 1e-12 else pv[t]
    rp = pd.Series(rp, index=close.index)
    out = (close - rp) / close
    return out
