"""MOM — 动量因子

Category : 动量因子
Operator : momentum
Direction: +1 正相关
Source   : momentum.txt

Formula
-------
MOM_{i,t} = Close_{i,t-1} / Close_{i,t-12} - 1

Variable -> data field
----------------------
  Close      -> close        (t日的收盘价)

NOTE: Auto-generated by factor-forge from the structured factor JSON.
Review before production use.
"""

import numpy as np
import pandas as pd


def MOM(close, lag=12, skip=1):
    """Price momentum: return over [t-lag, t-skip]."""
    close = pd.Series(close).astype(float)
    out = close.shift(skip) / close.shift(lag) - 1.0
    return out
