"""REV — 短期反转因子

Category : 短期反转因子
Operator : reversal
Direction: +1 正相关
Source   : reversal.txt

Formula
-------
REV_{i,t} = -( Close_{i,t} / Close_{i,t-1} - 1 )

Variable -> data field
----------------------
  Close      -> close        (t日的收盘价)

NOTE: Auto-generated by factor-forge from the structured factor JSON.
Review before production use.
"""

import numpy as np
import pandas as pd


def REV(close, period=1):
    """Short-term reversal: negative of the most recent `period` return."""
    close = pd.Series(close).astype(float)
    out = -close.pct_change(periods=period)
    return out
