"""VOL — 已实现波动率因子

Category : 已实现波动率因子
Operator : volatility
Direction: -1 负相关
Source   : volatility.txt

Formula
-------
VOL_{i,t} = std( r_{i,t-20:t} ) * sqrt(252)

Variable -> data field
----------------------
  r_{i,t}    -> close        (t日的日收益率，由收盘价计算；)
  std        -> ?            (滚动窗口内的标准差)

NOTE: Auto-generated by factor-forge from the structured factor JSON.
Review before production use.
"""

import numpy as np
import pandas as pd


def VOL(close, window=20, annualize=True):
    """Realized volatility over a rolling window."""
    close = pd.Series(close).astype(float)
    ret = close.pct_change()
    vol = ret.rolling(window).std()
    if annualize:
        vol = vol * np.sqrt(252)
    return vol
